WebBanHang/Areas/Admin/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
namespace WebBanHang.Areas.Admin.Controllers
{
    public class DefaultController : Controller
    {
        SaleStoreDB db = new SaleStoreDB();
        // GET: Admin/Default
        public ActionResult Index()
        {
            ViewBag.Product_Count = db.Products.Count();
            ViewBag.Orders = db.Orders.Count();
            ViewBag.Customers = db.Customers.Count();
            
            return View();
        }
    }
}

WebBanHang/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
using PagedList;
using System.Data.Entity;
namespace WebBanHang.Controllers
{
    public class ProductController : Controller
    {
        SaleStoreDB db = new SaleStoreDB();
        // GET: Product
        public ActionResult Index(int ?CatID,String SupID, int ?page)
        {
            //var dsProduct = db.Products.Where(x => x.CategoryId == CatID).ToList();
            //ViewBag.TieuDe = db.Categories.Find(CatID).Name;
            List<Product> dsProduct;
            if(CatID!=null)
            {
                dsProduct = db.Products.Where(x => x.CategoryId == CatID).ToList();
                ViewBag.TieuDe = db.Categories.Find(CatID).Name;
                
            }
            else if(SupID!=null)
            {
                dsProduct = db.Products.Where(x => x.SupplierId.Equals(SupID)).ToList();
                ViewBag.TieuDe = db.Suppliers.Find(SupID).Name;
            }
            else
            {
                dsProduct = db.Products.ToList();
                ViewBag.TieuDe = "Danh Sách sản phẩm";
            }
            int pageSize = 6;
            int  pageNumber = page ?? 1;
            ViewBag.CatID = CatID;
            ViewBag.SupID = SupID;
            return View(dsProduct.ToPagedList(pageNumber, pageSize));
           
        }
        public ActionResult search(int? page, string name = "")
        {
            int pageSize = 8;
            int pageNumber = page ?? 1;
            List<Product> products = null;
            if (name == "")
            {
                products = db.Products.Include(p => p.Category).Include(p => p.Supplier).OrderBy(x => x.Name).ToList();
            }
            
            else
                products = db.Products.Include(p => p.Category).Include(p => p.Supplier).Where(y => y.Name.Contains(name)).OrderBy(z => z.Name).ToList();
            ViewBag.name = name;
            return View(products.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult viewALLnew(int? page)
        {
            int pageSize = 8;
            int pageNumber = page ?? 1;
            List<Product> products  = db.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(x => x.ProductId).ToList();
            
            return View(products.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Detail(int ProID = 101)
        {
            
            var p = db.Products.Find(ProID);
            if (p == null)
                return HttpNotFound();

            return View(p);
        }
    }
}

WebBanHang/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class ShoppingCartController : Controller
    {
        SaleStoreDB db = new SaleStoreDB();
        // GET: ShoppingCart
        public ActionResult AddToCart(int ProID)
        {
     
            Cart cart = GetCart();
            Product p = db.Products.Find(ProID);
            //Gọi hàm thêm sản phầm từ lớp Cart của Namespace Models;
            cart.AddItem(p, 1);
          
            return RedirectToAction("ViewCart");
        }
        public ActionResult ViewCart()
        {
            Cart cart = GetCart();
            return View(cart);
        }
        public Cart GetCart()
        {
            Cart cart = (Cart)Session["CART"];
            if(cart==null)
            {
                cart = new Cart();
                Session["CART"] = cart;
            }
            return cart;
        }
        public ActionResult UpdateCart(int[] ProID, int[] Quantity)
        {
            //lấy giỏ hàng từ Session
            Cart cart = GetCart();
            //duyet qua cac ma san pham trong mang
            for (int i = 0; i < ProID.Length; i++)
            {
                //truy van thong tin san pham them ma san pham
                Product p = db.Products.Find(ProID[i]);
                //goi ham cap nhat so luong cho san pham tuong ung
                cart.UpdateItem(p, Quantity[i]);
            }
            return RedirectToAction("ViewCart");
        }
        public ActionResult DeleteCart(int[] ProID)
        {
            //lấy giỏ hàng từ Session
            Cart cart = GetCart();
            //duyet qua cac ma san pham trong mang
            for (int i = 0; i < ProID.Length; i++)
            {
                //truy van thong tin san pham them ma san pham
                Product p = db.Products.Find(ProID[i]);
                //goi ham cap nhat so luong cho san pham tuong ung
                cart.DeleteItem(p);
            }
            return RedirectToAction("ViewCart");
        }
    }
}

WebBanHang/Views/Shared/_ChungLoai.cshtml
@using WebBanHang.Models
@{ 
    var db = new SaleStoreDB();
    var dsChungLoai = db.Categories.ToList();
}
<div class="list-group">
    <a href="#" class="list-group-item active">
        <span class="glyphicon glyphicon-list"></span>
    CHỦNG LOẠI</a>
    @foreach(var item in dsChungLoai)
    {
        <a href="@Url.Action("Index","Product",new { CatID=item.CategoryId})" class="list-group-item">@item.Name
        <span class="badge">@item.Products.Count</span>
    </a>
    }

</div>

WebBanHang/Views/Shared/_Layout.cshtml
@{ 

    var cart = Session["CART"] as WebBanHang.Models.Cart;
 }

<!DOCTYPE html>
<!--
    ustora by freshdesignweb.com
    Twitter: https://twitter.com/freshdesignweb
    URL: https://www.freshdesignweb.com/ustora/
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ustora Demo</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/frontEnd/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/frontEnd/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Content/frontEnd/css/owl.carousel.css">
    <link rel="stylesheet" href="~/Content/frontEnd/style.css">
    <link rel="stylesheet" href="~/Content/frontEnd/css/responsive.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="#"><i class="fa fa-user"></i> My Account</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                             <li><a href="cart.html"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="checkout.html"><i class="fa fa-user"></i> Checkout</a></li>
                            <li><a href="#"><i class="fa fa-user"></i> Login</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">USD</a></li>
                                    <li><a href="#">INR</a></li>
                                    <li><a href="#">GBP</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->

    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="@Url.Action("Index", "Home")"><img src="~/Content/frontEnd/img/logo.png"></a></h1>
                    </div>
                </div>
             @if (cart==null)
             {
                <div  class="col-sm-6">
                    <div class="shopping-item">
                        <a href="@Url.Action("ViewCart","ShoppingCart")"  >Cart - <span class="cart-amunt"> 0 </span> <i class="fa fa-shopping-cart"></i> <span class="product-count">0</span></a>
      
                    </div>
                </div>
             }
             else
             {
                <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="@Url.Action("ViewCart","ShoppingCart")">Cart - <span class="cart-amunt">@cart.SubTotal </span> <i class="fa fa-shopping-cart"></i> <span class="product-count">@cart.Items.Count()</span></a>

                    </div>
                </div>

             }

            </div>
        </div>
    </div> <!-- End site branding area -->

    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li><a href="shop.html">Shop page</a></li>
                        <li><a href="single-product.html">Single product</a></li>
                        <li><a href="cart.html">Cart</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="#">Category</a></li>
                        <li><a href="#">Others</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->

    @RenderBody()

    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>u<span>Stora</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Vendor contact</a></li>
                            <li><a href="#">Front page</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="#">Mobile Phone</a></li>
                            <li><a href="#">Home accesseries</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Computer</a></li>
                            <li><a href="#">Gadets</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="@Url.Action("Index","Default",new { @area="Admin"})" target="_blank">Quản trị</a></p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->
    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>
    
    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="~/Content/frontEnd/js/owl.carousel.min.js"></script>
    <script src="~/Content/frontEnd/js/owl.carousel.min.js"></script>
    <script src="~/Content/frontEnd/js/jquery.sticky.js"></script>

    <!-- jQuery easing -->
    <script src="~/Content/frontEnd/js/jquery.easing.1.3.min.js"></script>

    <!-- Main Script -->
    <script src="~/Content/frontEnd/js/main.js"></script>

    <!-- Slider -->
    <script type="text/javascript" src="~/Content/frontEnd/js/bxslider.min.js"></script>
    <script type="text/javascript" src="~/Content/frontEnd/js/script.slider.js"></script>
</body>
</html>

WebBanHang/Views/Shared/_NhaCungCap.cshtml
@using WebBanHang.Models
@{ 
    SaleStoreDB db = new SaleStoreDB();
    var dsNhaCungCap = db.Suppliers.ToList();
}
<div class="list-group">
   <a href="#" class="list-group-item active">Nhà cung cấp</a>
    @foreach (var item in dsNhaCungCap)
    {
        <a href="@Url.Action("Index", "Product", new { SupID = item.SupplierId })" class="list-group-item">@item.Name
        <span class="badge">@item.Products.Count</span>
    </a>
    }
 </div>

WebBanHang/Views/Shared/_sidebar.cshtml
<div class="single-sidebar">
    <h2 class="sidebar-title">Search Products</h2>
    @using (Html.BeginForm("search", "Product", FormMethod.Post, new { @class = "input-group" }))
    {
        <input  name="name"type="text" placeholder="Search products...">
        <input type="submit" value="Search">
    }
</div>

<div class="single-sidebar">
    <h2 class="sidebar-title">Products</h2>
    <div class="thubmnail-recent">
        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
        <h2><a href="">Sony Smart TV - 2015</a></h2>
        <div class="product-sidebar-price">
            <ins>$700.00</ins> <del>$100.00</del>
        </div>
    </div>
    <div class="thubmnail-recent">
        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
        <h2><a href="">Sony Smart TV - 2015</a></h2>
        <div class="product-sidebar-price">
            <ins>$700.00</ins> <del>$100.00</del>
        </div>
    </div>
    <div class="thubmnail-recent">
        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
        <h2><a href="">Sony Smart TV - 2015</a></h2>
        <div class="product-sidebar-price">
            <ins>$700.00</ins> <del>$100.00</del>
        </div>
    </div>
    <div class="thubmnail-recent">
        <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
        <h2><a href="">Sony Smart TV - 2015</a></h2>
        <div class="product-sidebar-price">
            <ins>$700.00</ins> <del>$100.00</del>
        </div>
    </div>
</div>

<div class="single-sidebar">
    <h2 class="sidebar-title">Recent Posts</h2>
    <ul>
        <li><a href="">Sony Smart TV - 2015</a></li>
        <li><a href="">Sony Smart TV - 2015</a></li>
        <li><a href="">Sony Smart TV - 2015</a></li>
        <li><a href="">Sony Smart TV - 2015</a></li>
        <li><a href="">Sony Smart TV - 2015</a></li>
    </ul>
</div>